### ISSUE TITLE
Create SuggestionItemImpl class

### ISSUE THREAD

**Issue by johannagwan** [AY1920S2-CS2103T-W17-2/main#112]
To create a `SuggestionItemImpl` concrete class which implements `SuggestionItem` interface.

`model --> suggestion --> SuggestionItemImpl`

**Comment by kevinputera** [comment]
Hey @johannagwan ! Just nitpicking here, but I feel like the `model --> suggestion --> SuggestionItemImpl` is not that descriptive.
