### ISSUE TITLE
Update SuggestionCommandParser Interface

### ISSUE THREAD

**Issue by johannagwan** [AY1920S2-CS2103T-W17-2/main#195]
To change the method `parse(String userInput)` to `parse(String userInput, Model model)`. This is so that in the individual `SuggestionCommandParser` classes (e.g. `OpenSuggestionCommandParser`, `NewSuggestionCommandParser`, etc.) we can access the `model` to convert the user input's `RelativePath` to `AbsolutePath`.

**Comment by kevinputera** [comment]
Closing this @johannagwan !
