### ISSUE TITLE
Initialise a commandInputModel [Model]

### ISSUE THREAD

**Issue by HemanshuGandhi** [AY1920S2-CS2103T-W17-2/main#25]
Add a commandInputModel interface that extends the Model interface. For behavior: create an ObservableList for text that can be 'observed'.

**Comment by kevinputera** [comment]
@HemanshuGandhi Hey hemanshu!

For this, take a look at the [StringProperty](https://docs.oracle.com/javase/8/javafx/api/javafx/beans/property/StringProperty.html) class from JavaFX.

Take a look [here](https://github.com/kevinputera/javafx-todo/blob/master/src/main/java/javafx/todo/model/TodoInputModelImpl.java) in case you would like to see an example!
