### ISSUE TITLE
Revamp SuggestionItem and SuggestionItemImpl

### ISSUE THREAD

**Issue by johannagwan** [AY1920S2-CS2103T-W17-2/main#264]
Currently, this is our `SuggestionItemImpl`:
```java
public class SuggestionItemImpl implements SuggestionItem {
    private String displayText;
    private Runnable action;

    public SuggestionItemImpl(String displayText, Runnable action) {
        this.displayText = displayText;
        this.action = action;
    }

    @Override
    public String getDisplayText() {
        return displayText;
    }

    @Override
    public Runnable getAction() {
        return action;
    }
}
```

Since in `SearchSuggestionCommand` we would need to store the number of occurrences of a keyword (can be a sentence) and display it in the View, as @kevinputera suggested we can replace `String getDisplayText()` with `Optional<String> getProperty(String key)` and do the key-value mappings at the constructor.

Therefore, I'd like to propose the new `SuggestionItemImpl` class as such:
```java
public class SuggestionItemImpl implements SuggestionItem {
    private Runnable action;
    private HashMap<String, String> hmap;

    public SuggestionItemImpl(String displayText, Runnable action) {
        this.action = action;

        hmap = new HashMap<>();
        hmap.put("displayText", displayText);
    }

    public SuggestionItemImpl(String displayText, int frequency, Runnable action) {
        this.action = action;

        hmap = new HashMap<>();
        hmap.put("displayText", displayText);
        hmap.put("frequency", Integer.toString(frequency));
    }

    @Override
    public Optional<String> getProperty(String key) {
        return Optional.ofNullable(hmap.get(key));
    }

    @Override
    public Runnable getAction() {
        return action;
    }
}
```

**Comment by kevinputera** [comment]
@johannagwan FYI, a [refactor](https://en.wikipedia.org/wiki/Code_refactoring) by definition shouldn't involve any change in API. This is better framed as "revamp" or "update" or something similar.

**Comment by johannagwan** [comment]
> @johannagwan FYI, a [refactor](https://en.wikipedia.org/wiki/Code_refactoring) by definition shouldn't involve any change in API. This is better framed as "revamp" or "update" or something similar.

Oh alright, will change the name!
