### ISSUE TITLE
Limit max Suggestions List Height [View]

### ISSUE THREAD

**Issue by HemanshuGandhi** [AY1920S2-CS2103T-W17-2/main#322]
Currently, the max height of the Suggestions List is proportional to the available vertical space over the note block. This is not ideal, as it will completely cover the text if there are too many suggestions. 

Hence, the plan is to limit the height of the List, with the option for scrolling. 

![Screen Shot 2020-04-01 at 1 58 31 PM](https://user-images.githubusercontent.com/22761280/78104216-5b233c00-7421-11ea-96a1-620588506fe3.png)

**Comment by firzanarmani** [comment]
Closed by #311
