### ISSUE TITLE
[Bug] Unhandled edge case for note starting with '/'

### ISSUE THREAD

**Issue by HemanshuGandhi** [AY1920S2-CS2103T-W17-2/main#323]
Expected behavior should be a helpful message. Let's see how we can better handle such IllegalArgumentException. Should not appear as a bug in the console

See the error log in the image below. (click to enlarge)

![Screen Shot 2020-04-01 at 2 04 55 PM](https://user-images.githubusercontent.com/22761280/78104632-177d0200-7422-11ea-9d70-384bf228e00a.png)

**Comment by ljiazh3ng** [comment]
@firzanarmani Do let me know if you decide to throw any additional runtime exception to solve this.
I'll then update the Command class and Parser class to catch it !

**Comment by firzanarmani** [comment]
Closed by #328
