### ISSUE TITLE
Create a custom implementation of a path

### ISSUE THREAD

**Issue by kevinputera** [AY1920S2-CS2103T-W17-2/main#82]
We need a custom class representing a path to a `Block`.

**Comment by kevinputera** [comment]
Proposed by @ljiazh3ng at #8 

UPDATE:
- Changed `getPath` to `getPaths`
- Changed return type of `getPaths` from `String[]` to `List<String>`
- Added a `boolean isAbsolute()` method

```java
interface Path {
  List<String> getPaths();
  boolean isAbsolute();
}
```

**Comment by kevinputera** [comment]
Hey @ljiazh3ng, I moved your proposed implementation of the `Path` interface from #8 to here, for ease of reference.

In addition, let's change `String[]` to `List<String>` (since `List` is more convenient than a regular array) and add a `isAbsolute()` method!

**Comment by kevinputera** [comment]
@firzanarmani Hey firzan, please take a look and let me know what you think!

**Comment by firzanarmani** [comment]
@kevinputera I think this is good enough for now!
