### ISSUE TITLE
Create AbsolutePathCorrectionEngine class

### ISSUE THREAD

**Issue by kevinputera** [AY1920S2-CS2103T-W17-2/main#99]
**EDIT**:
1. Rectified SuggestionEngine -> CorrectionEngine
2. Added proposed implementation
3. Add gotchas

---

As described in #97, I'll be implementing the `AbsolutePathCorrectionEngine` class.

**Proposed API (I'm only showing the important methods below)**:

```java
class AbsolutePathCorrectionEngine implements CorrectionEngine<AbsolutePath> {
  public AbsolutePathCorrectionEngine(Model model) { }
  public CorrectionResult<AbsolutePath> correct(AbsolutePath inputPath) { } 
}
```

**Proposed Implementation (step by step)**:
1. Get the components of the uncorrected absolute path. For example, the path `/path/to/blo` will have the components `["path", "to", "blo"]`.
2. Compare this uncorrected path component-by-component with a list of possible paths. For every two components, compute their distance and add it to the total sum of the distance between two paths.
3. Return the path with the least total distance.

**Gotchas (based on the current implementation)**:
1. Currently, I'm not prioritizing a longer match over a shorter match. That is, if the input is `/path/to/bloc`, the correction engine might return `/path/to/blo` over `/path/to/block` (if time allows, I'll create another issue to address this)

#### How to use
1. I'd imagine that you instantiate this class during the creation of both `SuggestionEngine` and `Parser`. During this instantiation phase, you'll supply the app's model to `AbsolutePathCorrectionEngine`'s constructor.
2. After that, whenever you receive user input, you'll call the correct method. You're guaranteed to receive a corrected path (or error if `inputPath` is not understandable)

**Comment by kevinputera** [comment]
@johannagwan @ljiazh3ng Please help check this out!

**Comment by johannagwan** [comment]
Hi @kevinputera , sorry for the late reply. I think the methods look good! May I ask regarding these 2 things:
- So you are also going to make RelativePathCorrectionEngine class right?
- Why does AbsolutePathCorrectionEngine implement SuggestionEngine<AbsolutePath> and not CorrectionEngine<AbsolutePath>? or is it a typo?

**Comment by kevinputera** [comment]
> So you are also going to make RelativePathCorrectionEngine class right?

Nope, there will only be an `AbsolutePathCorrectionEngine`. It's pretty difficult to correct a relative path, due to the nature of it being relative (which makes it possible to have multiple relative paths pointing to the same path). It is definitely possible to create a `RelativePathCorrectionEngine`, but I think for now I'll just create an `AbsolutePathCorrectionEngine`.

> Why does AbsolutePathCorrectionEngine implement SuggestionEngine and not CorrectionEngine? or is it a typo?

Oh right, thanks for the catch. It should be `CorrectionEngine<AbsolutePath>`
